version: '3.8'
services:
  ae_mind:
    build: .
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m ae_mind.src.introspective_parser.run_pipeline input.txt --out output.md
