# Analyst Agent Configuration
name: analyst_agent
version: 1.0
llm_client: openai

# Core Settings
role: data_analysis
priority: 3
timeout: 300
retry_limit: 3

# Performance Settings
max_concurrent_tasks: 8
memory_limit_mb: 1024
log_level: INFO

# ASL Integration
asl_tags:
  - analysis_type
  - confidence_score
  - insight_category
  - evidence_links

# Analysis Types
analysis_categories:
  - pattern_recognition
  - trend_analysis
  - anomaly_detection
  - correlation_studies
  - impact_assessment

# Processing Configuration
analysis_settings:
  confidence_threshold: 0.8
  max_depth: 5
  correlation_minimum: 0.6
  sample_size_minimum: 100

# Output Configuration
output_formats:
  - analytical_report
  - statistical_summary
  - visualization_data
  - recommendation_set

# Dependencies
required_modules:
  - statistical_engine
  - ml_processor
  - visualization_generator

# Model Configuration
models:
  - type: statistical
    enabled: true
    parameters:
      confidence_level: 0.95
  - type: machine_learning
    enabled: true
    parameters:
      training_iterations: 1000

# Recovery Settings
error_handling:
  max_retries: 3
  backoff_factor: 1.5
  recovery_strategies:
    - simplified_analysis
    - partial_results
    - alternative_methods

# Monitoring
metrics:
  - analysis_accuracy
  - processing_time
  - insight_quality
  - model_performance

# Security
access_level: data_analysis
encryption_required: true
auth_required: true
