# Synthesis Agent Configuration
name: synthesis_agent
version: 1.0
llm_client: openai

# Core Settings
role: output_synthesis
priority: 5
timeout: 300
retry_limit: 3

# Performance Settings
max_concurrent_tasks: 4
memory_limit_mb: 1024
log_level: INFO

# ASL Integration
asl_tags:
  - synthesis_stage
  - component_type
  - integration_status
  - quality_metrics

# Synthesis Components
component_types:
  - analysis_results
  - generated_content
  - documentation
  - metrics
  - recommendations

# Integration Settings
integration_config:
  quality_threshold: 0.9
  consistency_check: true
  cross_reference_enabled: true
  version_tracking: true

# Output Configuration
output_formats:
  - comprehensive_report:
      format: markdown
      include_toc: true
      include_metrics: true
  - executive_summary:
      format: pdf
      max_length: 1000
  - technical_documentation:
      format: html
      include_diagrams: true

# Dependencies
required_components:
  - document_processor
  - diagram_generator
  - cross_referencer
  - quality_checker

# Synthesis Rules
synthesis_rules:
  - rule: consistency_check
    enabled: true
    severity: high
  - rule: completeness_check
    enabled: true
    severity: high
  - rule: format_validation
    enabled: true
    severity: medium

# Recovery Settings
error_handling:
  max_retries: 3
  backoff_factor: 1.5
  recovery_strategies:
    - partial_synthesis
    - component_isolation
    - manual_intervention

# Quality Assurance
quality_checks:
  - completeness
  - consistency
  - readability
  - technical_accuracy

# Monitoring
metrics:
  - synthesis_quality
  - integration_success_rate
  - processing_time
  - error_rate

# Security
access_level: system
encryption_required: true
auth_required: true

# Optimization
optimization:
  parallel_processing: true
  cache_enabled: true
  incremental_updates: true
